name: Release

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SP_CI_AT }}

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'

      # Prepare
      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      # Publish to NPM
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: npm publish

      # Deploy to CDN (trigger)
      - name: Tirgger deploy to CDN
        run: |
          git tag deploy
          git push origin HEAD:main deploy

      # Bump version to next snapshot
      - name: Bump snapshot version
        run: |
          npm run bump -- --version=patch --snapshot
          npm install
          echo "SNAPSHOT_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      - name: Push changes
        run: |
          git fetch
          git config user.email "gullerya@gmail.com"
          git config user.name "sign-pad CI"
          git add --all
          git commit -m "set version to ${{ env.SNAPSHOT_VERSION }}"
          git push origin HEAD:main