name: Deploy to CDN

on:
  push:
    tags:
      - deploy

jobs:
  release-deploy:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.SP_CI_AT }}

      - name: Delete temporary trigger tag
        run: git push origin --delete deploy

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install
        run: npm ci

      # Get release version
      - name: Get release version
        run: echo "RELEASE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV

      # Build
      - name: Build
        run: npm run build

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET }}
        run: aws s3 sync ./dist s3://${{ secrets.AWS_LIBS_BUCKET }}/sign-pad/${{ env.RELEASE_VERSION }} --delete --cache-control public,max-age=172800,immutable
